# encoding: utf-8
module Holidays
  # This file is generated by the Ruby Holidays gem.
  #
  # Definitions loaded: data/us_custom.yaml
  #
  # To use the definitions in this file, load it right after you load the 
  # Holiday gem:
  #
  #   require 'holidays'
  #   require 'holidays/us_custom'
  #
  # All the definitions are available at https://github.com/alexdunae/holidays
  module US_CUSTOM # :nodoc:
    def self.defined_regions
      [:us_custom]
    end

    def self.holidays_by_month
      {
              1 => [{:mday => 1, :observed => lambda { |date| Holidays.to_weekday_if_weekend(date) }, :observed_id => "to_weekday_if_weekend", :name => "New Year's Day", :regions => [:us_custom]},
            {:wday => 1, :week => 3, :name => "Martin Luther King, Jr. Day", :regions => [:us_custom]}],
      2 => [{:wday => 1, :week => 3, :name => "Presidents' Day", :regions => [:us_custom]}],
      5 => [{:wday => 1, :week => -1, :name => "Memorial Day", :regions => [:us_custom]}],
      7 => [{:mday => 4, :observed => lambda { |date| Holidays.to_weekday_if_weekend(date) }, :observed_id => "to_weekday_if_weekend", :name => "Independence Day", :regions => [:us_custom]}],
      9 => [{:wday => 1, :week => 1, :name => "Labor Day", :regions => [:us_custom]}],
      10 => [{:wday => 1, :week => 2, :name => "Columbus Day", :regions => [:us_custom]}],
      11 => [{:mday => 11, :observed => lambda { |date| Holidays.to_weekday_if_weekend(date) }, :observed_id => "to_weekday_if_weekend", :name => "Veterans Day", :regions => [:us_custom]},
            {:wday => 4, :week => 4, :name => "Thanksgiving", :regions => [:us_custom]}],
      12 => [{:mday => 25, :observed => lambda { |date| Holidays.to_weekday_if_weekend(date) }, :observed_id => "to_weekday_if_weekend", :name => "Christmas Day", :regions => [:us_custom]}]
      }
    end
  end


end

Holidays.merge_defs(Holidays::US_CUSTOM.defined_regions, Holidays::US_CUSTOM.holidays_by_month)
